#Developed by: _ItsAndrew_
#This file is for configuring the main parts of the plugin

chat-prefix: "&f&l[&6&lTH&f&l]" #This is the prefix that shows up in the chat

toggle-fireworks-effect: true #Toggle the fireworks effect when a player clicks on a treasure
fw-main-color: "#5d30bf"  #Use HEX COLORS
fw-second-color: "#23bad9" #Use HEX COLORS

#Configure the /eog enable command
teleport-location-x:
teleport-location-y:
teleport-location-z:
title: "" #Use "&" for style
subtitle: "" #Use "&" for style

#Configure the start-book. It is the book that appears right after you enable the event.
start-book:
  toggle: true #true(yes) / #false(no)
  delay: 2 #In seconds
  author: "&cServer Staffs"
  title: "&6&lECHOES OF GOLD - INFO"
  pages: #Use '\n' to go on a new line in a page
    - "&5Welcome, adventurer!\n\n&6The night of terror begins...\n3 cursed chests await for you in the Overworld.\n\n&cFind them before they find you."
    - "&7Each chest holds &eancient treasures&7.\nBut beware...\nSome are guarded by monsters.\n\n&4Good luck!"

#Configure general messages. Use "&" for style
treasure-already-found: "&cYou have &lalready found &cthis treasure!" #Use & for style
treasure-found: "&aYou have found a &ltreasure&a!"
player-found-all-treasures: "&6&lGG! &6You have found all the treasures!"
treasure-has-no-rewards: "&cThis treasure does not have any rewards. Contact the server administrators about this!"
no-inventory-space-message:
hints-no-books-configured: "&cThere are no books configured."
hint-not-found-yet: "&cYou have not found this hint yet!"

#Configure the messages/titles/subtitles during the event. Use '&' for style.
toggle-event-messages: true
event-three-quarters-time:
  toggle: true
  chat-message-lines: #Use %three_quarters_time% to display 3/4 of the time left
    - "&a&lTIME LEFT: &a%three_quarters_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&aHURRY!"
  subtitle:
    message: "&aOnly &l%three_quarters_time% seconds &aleft!"

event-half-time:
  toggle: true
  chat-message-lines: #Use %half_time% to display 1/2 of the time left
    - "&a&lTIME LEFT: &a%half_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&aHURRY!"
  subtitle:
    message: "&aOnly &l%half_time% &aleft!"

event-one-quarter-time:
  toggle: true
  chat-message-lines: #Use %one_quarter_time% to display 1/4 of the time left
    - ""
  toggle-title-subtitle: false
  title:
    message: ""
  subtitle:
    message: ""

#Configure the Hints GUI settings
hints-gui:
  gui-rows: 6 #Value must be between 1 and 6. Each row has 9 slots => 9 slots-minimum, 54 slots-maximum
  gui-title: "Hints" #You can use & styles!

  known-hint-lore:
    - ""
    - "&aâœ” Unlocked"

  unknown-hint-title: "&c&l???"
  unknown-hint-lore:
    - ""
    - "&eðŸ”’ &lLocked"

  toggle-decorations: true #true(yes)/false(no)
  decoration-material: black_stained_glass_pane

  info-item-toggle: true #true(yes)/false(no)
  info-item-slot: 4 #The slot for the info item
  info-item-title: "&fChoose a hint to open" #Use '&' for styles
  info-item-material: oak_sign #The material for the info item

  #Configure the exit-button
  gui-exit-button:
    toggle: true #true(yes) / false(no)
    slot: 40
    material: red_concrete #The item that the button will have
    title: "&c&lEXIT"

  #Configure the no-hints-item. It appears if there aren't any hints created
  gui-no-hints-item:
    chat-message: "&cThere are no hints configured for this event!"
    material: barrier
    slot: 22
    title: "&cThere are no hints configured"

#Configure every sound for the plugin. For checking AND hearing every sound, run /playsound in minecraft, then write what is after "minecraft:"
#As for the volume and pitch, the default value is 1
start-event-sound: "entity.wither.spawn"
ses-volume: 1
ses-pitch: 1

event-three-quarter-time-sound: "block.note_block.pling"
etqts-volume: 1
etqts-pitch: 1

event-half-time-sound: "block.note_block.pling"
ehts-volume: 1
ehts-pitch: 1

event-one-quarter-time-sound: "block.note_block.pling"
eoqts-volume: 1
eoqts-pitch: 1

exit-button-sound: "ui.button.click"
ebs-volume: 1
ebs-pitch: 1

player-clicked-on-unknown-hint-sound: "entity.enderman.teleport"
pcouhs-volume: 1
pcouhs-pitch: 1

no-hints-item-sound: "entity.villager.no"
nhis-volume: 1
nhis-pitch: 0.8

treasure-found-sound: "entity.enderman.teleport"
tfs-volume: 1
tfs-pitch: 1

treasure-has-no-items-sound: "entity.villager.no"
thni-volume: 1
thni-pitch: 1

no-inventory-space-sound: "entity.enderman.teleport"
niss-volume: 1
niss-pitch: 1

treasure-click-sound: "entity.experience_orb.pickup"
tcs-volume: 1
tcs-pitch: 1.2

hint-open-sound: "item.book.page_turn"
hos-volume: 1
hos-pitch: 1

#Configure the treasures custom head
#For this you need to go to "https://minecraft-heads.com/", search for a desired custom head, then copy and paste the VALUE
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGJmNzJiNmZjZGM4Zjk1ZGYyOGYwNmY0MTUyZWE4YzliZTM4ZGEyODViMmNlZTA0ZTViZWQyMTUzYjM4OWQ5YiJ9fX0="

#Configure the particles.
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html <- go here for all available particles (CAPS matter)
treasures-particle: PORTAL
treasure-found-particle: CRIT

#This is the duration of the whole event.
event-duration: "1m" #d -> days; h -> hours; m -> minutes; s -> seconds

#BOSS BAR
boss-bar: true #true(yes)/false(no)
bar-title: "&6&Treasure Hunt Active!"
bar-title-ended: "&c&lTreasure Hunt Ended! Thanks for your participation. "
bar-title-time-left: "&5&lTime left: %time_left%. &5TIP: Use &l/hints" #Use '%time_left%' for displaying the time.

#SCOREBOARD
#AVAILABLE PLACEHOLDERS:
#%player_name% -> Display's the player's IGN
#%topN_name% -> The top N player's IGN (N = {1,2,3})
#%topN_count% -> The top N player's treasures found (N = {1,2,3})
#%player_treasures% -> Displays the player's number of found treasures
#%max_treasures% -> Displays the max treasures of the event (configured in treasures.yml)
scoreboard: true #true(yes)/false(no)
scoreboard-interval: 1 #Updates the scoreboard in this interval of time (seconds)
scoreboard-title: "&fðŸ’Ž &6&lTREASURE HUNT &fðŸ’Ž"
scoreboard-lines:
  - "&aPlayer: &f%player_name%"
  - "&7----------------"
  - "&f&l[&aðŸ†&f&l] &1&lTOP 3 PLAYERS:"
  - "&6&l1. &6%top1_name% &7- &f%top1_count%"
  - "&e&l2. &e%top2_name% &7- &f%top2_count%"
  - "&c&l3. &c%top3_name% &7- &f%top3_count%"
  - "&7---------------"
  - "&f&l[&aðŸ’°&f&l] &aYour treasures found: &f%player_treasures%/%max_treasures%"
#P.S: I got the ASCII emojis from ChatGPT

#Configure the help command message
#Use '&' for color codes
help-message:
  title: "&f&l====[&6&lTREASURE HUNT HELP&f&l]===="
  lines:
    - ""
    - "&l/th enable &r-> enables the event"
    - "&l/th disable &r-> disables the event"
    - "&l/th reload &r-> reloads the config of the plugin"
    - "&l/th treasures &r-> opens the treasure manager"
    - "&l/th hints create <name> &r-> creates a book with that name"
    - "&l/th hints delete <name> &r-> deletes the book with that name"
    - "&l/th hints manage <name> &r-> helps managing the hints"