#Developed by: _ItsAndrew_

#Configure the /treasurehunt enable command
#Everything about it you can find here (tp location, sound, title, subtitle)
teleport-location-x: 32
teleport-location-y: 76
teleport-location-z: -113
teleport-location-sound: "ENTITY_WITHER_SPAWN" #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html <- all available sounds
title: "" #Use "&" for style
subtitle: "" #Use "&" for style

#Configure the treasures custom head
#For this you need to go to "https://minecraft-heads.com/", search for a desired custom head, then copy and paste the VALUE
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjExOTY3M2RiNjFlY2JkNDJiYjE0ZmJjYjU2MjMwZmM1ZDhkZjA4OWEwODE3ZWI5MDg4OWQ1MzhiOGExNzM4YiJ9fX0="

#Configure the particles that will spawn around the custom head. The structure is "Particle.<name in CAPS>", so only change the <>
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html <- go here for all available particles (CAPS matter)
particle: PORTAL

#Configure the Messages. Use "&" for style
treasure-already-found: "&f&l[&6&lTH&f&l] &cYou have &lalready found &cthis treasure!" #Use & for style
treasure-found: "&f&l[&6&lTH&f&l] &aYou have found a &ltreasure&a!"
player-found-all-treasures: "&f&l[&6&lTH&f&l] &6&lGG! &6You have found all the treasures!"

hints-no-books-configured: "&cThere are no books configured."
hint-not-found-yet: "&cYou have not found this hint yet!"
hints-gui-title: "Hints"
hints-locked-lore: "&8ðŸ”’ Locked"

#Configure the REWARDS
#Only modify the "minecraft:... <number>" part. <number> stands for QUANTITY!
reward-tiers:
  1: #As in the first treasure found by a player.
    commands:
      - "give %player% minecraft:iron_ingot 5"
      - "give %player% minecraft:iron_leggings 1"

#BOSS BAR
boss-bar: true #true(yes)/false(no)
bar-timer: "5m" #d - days; h - hours; m - minutes; s - seconds
duration: #DO NOT MODIFY
bar-title: "&6&Treasure Hunt Active!"
bar-title-ended: "&c&lTreasure Hunt Ended! Thanks for your participation. "
bar-title-time-left: "&5&lTime left: "
time-left-style: "&5&l" #This is ONLY for styles
bar-after-time: "&5  TIP: Use &l/hints"

#SCOREBOARD
#AVAILABLE PLACEHOLDERS:
#%player_name% -> Display's the player's IGN
#%topN_name% -> The top N player's IGN (N = {1,2,3})
#%topN_count% -> The top N player's treasures found (N = {1,2,3})
#%player_treasures% -> Displays the player's number of found treasures
#%max_treasures% -> Displays the max treasures of the event (configured in treasures.yml)
scoreboard: true #true(yes)/false(no)
scoreboard-interval: 1 #Updates the scoreboard in this interval of time (seconds)
scoreboard-title: "&fðŸ’Ž &6&lTREASURE HUNT &fðŸ’Ž"
scoreboard-lines:
  - "&aPlayer: &f%player_name%"
  - "&7----------------"
  - "&f&l[&aðŸ†&f&l] &1&lTOP 3 PLAYERS:"
  - "&6&l1. &6%top1_name% &7- &f%top1_count%"
  - "&e&l2. &e%top2_name% &7- &f%top2_count%"
  - "&c&l3. &c%top3_name% &7- &f%top3_count%"
  - "&7---------------"
  - "&f&l[&aðŸ’°&f&l] &aYour treasures found: &f%player_treasures%/%max_treasures%"
#P.S: I got the ASCII emojis from ChatGPT

#Configure the help command message
#Use '&' for color codes
help-message:
  title: "&f&l[&6&lTREASURE HUNT HELP&f&l]"
  lines:
    - "&l/treasurehunt enable &r-> enables the event"
    - "&l/treasurehunt disable &r-> disables the event"
    - "&l/treasurehunt reload &r-> reloads the config of the plugin"
    - "&l/treasurehunt books create <name> &r-> creates a book with that name" #The books will save in books.yml
    - "&l/treasurehunt books delete <name> &r-> deletes the book with that name"
    - "&l/treasurehunt books list &r-> gives a list of the created books"