#Developed by: _ItsAndrew_
#This file is for configuring the main parts of the plugin

chat-prefix: "&f&l[&6&lEOG&f&l]" #This is the prefix that shows up in the chat

toggle-fireworks-effect: true #Toggle the fireworks effect when a player clicks on a treasure
fw-main-color: "#5d30bf"  #Use HEX COLORS
fw-second-color: "#23bad9" #Use HEX COLORS

#Configure the /eog enable command
teleport-location-x:
teleport-location-y:
teleport-location-z:
title: "" #Use "&" for style
subtitle: "" #Use "&" for style

#Configure the start-book. It is the book that appears right after you enable the event.
start-book:
  toggle: true #true(yes) / #false(no)
  delay: 2 #Delay after the event starts (in seconds)
  author: "&cServer Staffs"
  title: "&6&lECHOES OF GOLD - INFO"
  pages: #Use '\n' to go on a new line in a page
    - "&5Welcome, adventurer!\n\n&6The night of terror begins...\n3 cursed chests await for you in the Overworld.\n\n&cFind them before they find you."
    - "&7Each chest holds &eancient treasures&7.\nBut beware...\nSome are guarded by monsters.\n\n&4Good luck!"

#Configure the Economy part of the plugin.
economy:
  toggle-using-economy: true

  #This pops a little message above the XP bar to the player when they find a treasure.
  #Use '%coins_amount%' to display how many coins the player got. Use '&' for styles
  action-bar-message: "&6You got %coins_amount% coins!"

  #Configure the internal economy. Note that you will need to restart the server if you make changes here when it is online.
  internal-economy:
    toggle: true #Setting this to false will use the Vault + An economy plugin instead of the internal one. Shop will also be disabled.
    database-system:
      type: sqlite #Use 'sqlite' if you run only one server. Use 'mysql' if you have multiple servers.
      file-name: "database.db" #This is only used if you use 'sqlite'!

      #These are the settings for the MySQL database. If you don't use MySQL, you can ignore this.
      host:
      port:
      database:
      username:
      password:

  #Configure the shop GUI. If the internal economy is disabled, the shop won't work.
  shop-gui:
    rows: 6 #Value must be between 1 and 6. Each row has 9 slots.
    title: "Event Shop"

    #Configure an exit item
    exit-item:
      material: red_concrete #The material of the item
      slot: 49
      display-name: "&c&lEXIT" #Use '&' for styles

    #Configure a 'no items' item
    no-items-item:
      material: barrier
      slot: 31
      display-name: "&eThere are no items set yet!"

    #Configure some decoration (on top of the gui)
    decoration:
      #If you set this to 'false', the shop items will appear from the top of the GUI
      toggle: true
      material: black_stained_glass_pane #Material for the deco
      display-name: " " #Leave like this for no display name

    #Configure the items for the shop. There is also an in game configuration for this (way easier to use :D).
    items:


#Configure general messages. Use "&" for style
treasure-already-found: "&cYou have &lalready found &cthis treasure!" #Use & for style
treasure-found: "&aYou have found a &ltreasure&a!"
player-found-all-treasures: "&6&lGG! &6You have found all the treasures!"
treasure-has-no-rewards: "&cThis treasure does not have any rewards. Contact the server administrators about this!"
no-inventory-space-message: "&cYou don't have enough inventory space!"
hints-no-books-configured: "&cThere are no books configured."
hint-not-found-yet: "&cYou have not found this hint yet!"

#Configure the messages/titles/subtitles during the event. Use '&' for style.
toggle-event-messages: true
event-three-quarters-time: #Configure the messages for the 3/4 of the time left
  toggle: true
  chat-message-lines: #Use %three_quarters_time% to display 3/4 of the time left
    - "&a&lTIME LEFT: &a%three_quarters_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle:
    message: "&aOnly &l%three_quarters_time% seconds &aleft!"

event-half-time: #Configure the messages for the 1/2 of the time left
  toggle: true
  chat-message-lines: #Use %half_time% to display 1/2 of the time left
    - "&a&lTIME LEFT: &a%half_time%"
    - "&aHurry!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle: #Same is this
    message: "&aOnly &l%half_time% &aseconds left!"

event-one-quarter-time: #Configure the messages for the 1/4 of the time left
  toggle: true
  chat-message-lines: #Use %one_quarter_time% to display 1/4 of the time left
    - "&a&lTIME LEFT: &a%one_quarter_time% seconds!"
  toggle-title-subtitle: true
  title:
    message: "&f&lHURRY!"
  subtitle:
    message: "&aOnly &a&l%one_quarter_time% &aseconds left!"

event-final-time: #This is the time when the event ends
  finish-event-message:
    toggle: true
    #PLACEHOLDERS:
    # - %topN_name% -> The top N player's IGN (N = {1,2,3})
    # - %topN_count% -> The top N player's treasures found (N = {1,2,3})
    message-lines:
      - "      &c&lEVENT FINISHED"
      - ""
      - ""
      - "  &e1) &l%top1_name% &e- &l%top1_count% &etreasures"
      - "  &72) &l%top2_name% &7- &l%top2_count% &7treasures"
      - "  &63) &l%top3_name% &6- &l%top3_count% &6treasures"
      - ""
      - ""
      - " &d&lTHANK YOU FOR PARTICIPATING!"
  final-countdown:
    seconds-to-start: 10 #Set the seconds from when the countdown will begin
    title: "&d&l%cooldown_time%" #Use %cooldown_time% to display the timer
    subtitle: ""
  #This is the title/subtitle that appears when the event finishes
  finish-event-title: "&e&lTREASURE HUNT IS FINISHED!"
  finish-event-subtitle: "&aCongrats %player_name% for your progress." #Use %player_name% to display the player's name

#Configure the Hints GUI settings
hints-gui:
  toggle-hints: true #If you want to use hints or not

  gui-rows: 6 #Value must be between 1 and 6. Each row has 9 slots => 9 slots-minimum, 54 slots-maximum
  gui-title: "Hints"

  #Configure the lore for an unlocked hint
  unlocked-hint-lore:
    - "&aâœ” &lUnlocked"
    - " "
    - "&7Click to open the hint"

  #Configure the lore for a locked hint
  locked-hint-lore:
    - "&eðŸ”’ &lLocked"
    - " "
    - "&cYou already found this treasure!"

  #Configure a 'Hints Item' during the event which players can right click on
  hints-item:
    toggle: true #Whether you want this item or not
    hotbar-slot: 8 #The slot in which the player will get this item. Values are from 0 to 8!
    material: enchanted_book
    display-name: "&6&lHINTS" #The display name of the item
    lore: #The lore of the item. Leave blank for none
      - " "
      - "&7Click to view hints for the treasures!"

  toggle-decorations: true #Whether you want decorations or not
  decoration-material: black_stained_glass_pane

  #Configure the info-item. Handy for displaying some tips/etc.
  info-item:
    toggle: true #Whether you want this item in your GUI or not
    slot: 4 #The slot for the item
    display-name: "&fChoose a hint to open" #Use '&' for styles
    material: oak_sign #The material

  #Configure the exit-button
  exit-button:
    toggle: true #Whether you want this button or not
    slot: 49
    material: red_concrete #The item that the button will have
    display-name: "&c&lEXIT"

  #Configure the no-hints-item. It appears if there aren't any hints created
  gui-no-hints-item:
    chat-message: "&eThere are no hints configured for this event."
    material: barrier
    slot: 22
    display-name: "&cThere are no hints configured. You are on your own!"

#Configure every sound for the plugin. For checking AND hearing every sound, run /playsound in minecraft, then write what is after "minecraft:"
#As for the volume and pitch, the default value is 1
start-event-sound: "entity.wither.spawn"
ses-volume: 1
ses-pitch: 1

countdown-sound: "block.note_block.hat"
cs-volume: 1
cs-pitch: 1

event-finish-sound: "entity.ender_dragon.death"
efs-volume: 1
efs-pitch: 1

event-three-quarter-time-sound: "block.note_block.hat"
etqts-volume: 1
etqts-pitch: 1

event-half-time-sound: "block.note_block.hat"
ehts-volume: 1
ehts-pitch: 1

event-one-quarter-time-sound: "block.note_block.hat"
eoqts-volume: 1
eoqts-pitch: 1

player-clicked-on-unknown-hint-sound: "entity.enderman.teleport"
pcouhs-volume: 1
pcouhs-pitch: 1

no-hints-item-sound: "entity.villager.no"
nhis-volume: 1
nhis-pitch: 0.8

treasure-found-sound: "entity.enderman.teleport"
tfs-volume: 1
tfs-pitch: 1

treasure-has-no-items-sound: "entity.villager.no"
thni-volume: 1
thni-pitch: 1

no-inventory-space-sound: "entity.enderman.teleport"
niss-volume: 1
niss-pitch: 1

treasure-click-sound: "entity.experience_orb.pickup"
tcs-volume: 1
tcs-pitch: 1.2

hint-open-sound: "item.book.page_turn"
hos-volume: 1
hos-pitch: 1

#Configure the treasures custom head
#For this you need to go to "https://minecraft-heads.com/", search for a desired custom head, then copy and paste the VALUE
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGJmNzJiNmZjZGM4Zjk1ZGYyOGYwNmY0MTUyZWE4YzliZTM4ZGEyODViMmNlZTA0ZTViZWQyMTUzYjM4OWQ5YiJ9fX0="

#Configure the particles. Try to play with all the offset/extra values :)
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html <- go here for all available particles
treasures-particle:
  toggle: true #Whether you want these particles or not
  particle: PORTAL
  count: 40
  offsetX: 0.4
  offsetY: 0.5
  offsetZ: 0.4
  extra: 0 #This is extra data for the particle, usually speed.

treasure-found-particle:
  toggle: true #Whether you want this particle or not
  particle: CRIT
  count: 30
  offsetX: 0.2
  offsetY: 0.3
  offsetZ: 0.2
  extra: 0 #Again, extra data for the particle, usually speed.

#This is the duration of the whole event.
event-duration: "1m" #d -> days; h -> hours; m -> minutes; s -> seconds

#BOSS BAR
boss-bar: true #true(yes)/false(no)
bar-title: "&6&Treasure Hunt Active!"
bar-title-ended: "&c&lTreasure Hunt Ended! Thanks for your participation. "
bar-title-time-left: "&5&lTime left: %time_left%. &5TIP: Use &l/hints" #Use '%time_left%' for displaying the time.
stop-boss-bar-interval: 10 #Stop the boss bar after <interval> seconds when event ends

#SCOREBOARD
#AVAILABLE PLACEHOLDERS:
#%player_name% -> Display's the player's IGN
#%topN_name% -> The top N player's IGN (N = {1,2,3})
#%topN_count% -> The top N player's treasures found (N = {1,2,3})
#%player_treasures% -> Displays the player's number of found treasures
#%max_treasures% -> Displays the max treasures of the event (configured in treasures.yml)
#%coins_gathered% -> Displays the coins the player found
scoreboard: true #true(yes)/false(no)
scoreboard-interval: 1 #Updates the scoreboard in this interval of time (seconds)
scoreboard-title: "&fðŸ’Ž &6&lTREASURE HUNT &fðŸ’Ž"
scoreboard-lines:
  - "&aPlayer: &f%player_name%"
  - "&7----------------"
  - "&f&l[&aðŸ†&f&l] &1&lTOP 3 PLAYERS:"
  - "&6&l1. &6%top1_name% &7- &f%top1_count%"
  - "&e&l2. &e%top2_name% &7- &f%top2_count%"
  - "&c&l3. &c%top3_name% &7- &f%top3_count%"
  - "&7---------------"
  - "&f&l[&aðŸŽ&f&l] &aTreasures Found: &f%player_treasures%/%max_treasures%"
  - "&f&l[&aðŸª™&f&l] &aCoins Gathered: &f%coins_gathered%" #This line will only appear if the Economy is toggled and working!

#Configure the help command message
#Use '&' for color codes
help-message:
  title: "&f&l====[&6&lTREASURE HUNT HELP&f&l]===="
  lines:
    - ""
    - "&l/th enable &r-> enables the event"
    - "&l/th disable &r-> disables the event"
    - "&l/th reload &r-> reloads the config of the plugin"
    - "&l/th treasures &r-> opens the treasure manager"
    - "&l/th hints create <name> &r-> creates a book with that name"
    - "&l/th hints delete <name> &r-> deletes the book with that name"
    - "&l/th hints manage <name> &r-> helps managing the hints"

#This is for saving the duration over time (in case of a server reload)
saving-duration: