#Developed by: _ItsAndrew_
#This file is for configuring the main parts of the plugin

chat-prefix: "&f&l[&6&lTH&f&l]" #This is the prefix that shows up in the chat

#Configure the start-book. It is the book that appears right after you enable the event.
start-book:
  toggle: true #true(yes) / #false(no)
  delay: 3 #In seconds
  gui-slot: 13
  author: "&cServer Staffs"
  title: "&6&lTREASURE HUNT - INFO"
  unlock-after: 0
  pages: #Use '\n' to go on a new line in a page
    - "&5Welcome, adventurer!\n\n&6The night of terror begins...\n3 cursed chests await for you in the Overworld.\n\n&cFind them before they find you."
    - "&7Each chest holds &eancient treasures&7.\nBut beware...\nSome are guarded by monsters.\n\n&4Good luck!"

#Configure the GUI settings
hints-gui:
  gui-rows: 6 #Value must be between 1 and 6. Each row has 9 slots => 9 slots-minimum, 54 slots-maximum
  gui-title: "Hints" #You can use & styles!

  #Configure the exit-button
  gui-exit-button:
    toggle: true #true(yes) / false(no)
    slot:
    material: red_concrete #The item that the button will have
    title: "&c&lEXIT"

  #Configure the no-hints-item. It appears if there aren't any hints created
  gui-no-hints-item:
    toggle: true #true(yes) / false(no)
    chat-message: "&cThere are no hints configured for this event!"
    material: oak_sign
    slot:
    title: "&cThere are no hints configured"
    lore: #You can use '&' styles!
      - ""

#Configure every sound for the plugin. For checking AND hearing every sound, run /playsound in minecraft, then write what is after "minecraft:"
#As for the volume and pitch, the default value is 1
start-event-sound: "entity.wither.spawn"
ses-volume: 1
ses-pitch: 1

exit-button-sound: "ui.button.click"
ebs-volume: 1
ebs-pitch: 1

no-hints-item-sound: "entity.villager.no"
nhis-volume: 1
nhis-pitch: 0.7

#Configure the /treasurehunt enable command
teleport-location-x:
teleport-location-y:
teleport-location-z:
title: "" #Use "&" for style
subtitle: "" #Use "&" for style

#Configure the treasures custom head
#For this you need to go to "https://minecraft-heads.com/", search for a desired custom head, then copy and paste the VALUE
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjExOTY3M2RiNjFlY2JkNDJiYjE0ZmJjYjU2MjMwZmM1ZDhkZjA4OWEwODE3ZWI5MDg4OWQ1MzhiOGExNzM4YiJ9fX0="

#Configure the particles that will spawn around the custom head. The structure is "Particle.<name in CAPS>", so only change the <>
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html <- go here for all available particles (CAPS matter)
particle: PORTAL

#Configure the Messages. Use "&" for style
treasure-already-found: "&f&l[&6&lTH&f&l] &cYou have &lalready found &cthis treasure!" #Use & for style
treasure-found: "&f&l[&6&lTH&f&l] &aYou have found a &ltreasure&a!"
player-found-all-treasures: "&f&l[&6&lTH&f&l] &6&lGG! &6You have found all the treasures!"

hints-no-books-configured: "&cThere are no books configured."
hint-not-found-yet: "&cYou have not found this hint yet!"
hints-locked-lore: "&8ðŸ”’ Locked"

#Configure the REWARDS
#Only modify the "minecraft:... <number>" part. <number> stands for QUANTITY!
reward-tiers:
  1: #As in the first treasure found by a player.
    commands:
      - "give %player% minecraft:iron_ingot 5"
      - "give %player% minecraft:iron_leggings 1"

#BOSS BAR
boss-bar: true #true(yes)/false(no)
bar-timer: "5m" #d - days; h - hours; m - minutes; s - seconds
duration: #DO NOT MODIFY
bar-title: "&6&Treasure Hunt Active!"
bar-title-ended: "&c&lTreasure Hunt Ended! Thanks for your participation. "
bar-title-time-left: "&5&lTime left: "
time-left-style: "&5&l" #This is ONLY for styles
bar-after-time: "&5  TIP: Use &l/hints"

#SCOREBOARD
#AVAILABLE PLACEHOLDERS:
#%player_name% -> Display's the player's IGN
#%topN_name% -> The top N player's IGN (N = {1,2,3})
#%topN_count% -> The top N player's treasures found (N = {1,2,3})
#%player_treasures% -> Displays the player's number of found treasures
#%max_treasures% -> Displays the max treasures of the event (configured in treasures.yml)
scoreboard: true #true(yes)/false(no)
scoreboard-interval: 1 #Updates the scoreboard in this interval of time (seconds)
scoreboard-title: "&fðŸ’Ž &6&lTREASURE HUNT &fðŸ’Ž"
scoreboard-lines:
  - "&aPlayer: &f%player_name%"
  - "&7----------------"
  - "&f&l[&aðŸ†&f&l] &1&lTOP 3 PLAYERS:"
  - "&6&l1. &6%top1_name% &7- &f%top1_count%"
  - "&e&l2. &e%top2_name% &7- &f%top2_count%"
  - "&c&l3. &c%top3_name% &7- &f%top3_count%"
  - "&7---------------"
  - "&f&l[&aðŸ’°&f&l] &aYour treasures found: &f%player_treasures%/%max_treasures%"
#P.S: I got the ASCII emojis from ChatGPT

#Configure the help command message
#Use '&' for color codes
help-message:
  title: "&f&l[&6&lTREASURE HUNT HELP&f&l]"
  lines:
    - "&l/treasurehunt enable &r-> enables the event"
    - "&l/treasurehunt disable &r-> disables the event"
    - "&l/treasurehunt reload &r-> reloads the config of the plugin"
    - "&l/treasurehunt books create <name> &r-> creates a book with that name" #The books will save in books.yml
    - "&l/treasurehunt books delete <name> &r-> deletes the book with that name"
    - "&l/treasurehunt books list &r-> gives a list of the created books"